name: CI

# Cancel previous runs that are not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  actions: read

jobs:
  ci:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compose short SHA
        run: |
          SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 080196/crawler-website
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}},prefix=,suffix=
          flavor: |
            latest=false
            suffix=-${{ env.SHORT_SHA }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}